### ISSUE TITLE
Docker images no longer on docker hub for ./test-blockchains docker-compose.yaml

### ISSUE THREAD

**Issue by washboardalex** [ConsenSys/gpact#143] opened 2022-10-06 08:46 UTC
The docker image `consensys/gpact/services/relayer` either does not exist any longer or is not authed for public access. Error messages:

`ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost.`

`ERROR: pull access denied for consensys/gpact/services/relayer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

If this is by design understood, just thought to check as this repo is very intriguing.

**Comment by drinkcoffee** [comment] 2022-10-07 01:16
I am almost certain the problem is the containers aren't built. Looking at the build steps, there are two missing steps.
https://github.com/ConsenSys/gpact/blob/main/docs/build.md

Try:

```
cd services/relayer
make docker
cd ../message-store
make docker
cd ../..
```

at that point, you should be able to:

```
cd test-blockchains
docker compose up

```

**Comment by drinkcoffee** [comment] 2022-10-07 02:29
This issue is being addressed here: https://github.com/ConsenSys/gpact/pull/144

**Comment by drinkcoffee** [comment] 2022-10-07 06:19
Revised documentation merged.

**Closed by drinkcoffee** 2022-10-07 06:19 UTC
